eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:7233/eureka/
      defaultZone: http://sunmi-node2:9098/eureka/,http://sunmi-node1:9097/eureka/,http://sunmi-node3:9099/eureka/
server:
  port: 12404
spring:
  application:
    name: proxy-service-heyan
logback:
   logdir: E:\\log-service-proxy-heyan-dev